name: Generate RSS feed

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Run Go script
      run: go run main.go -b news,g,vg -n 30 -p 1

    - name: Commit updated RSS feed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

        # Check if there are changes to rss.xml
        git diff --exit-code rss.xml || {
          git add rss.xml
          git commit -m "auto: update rss feed"
          git push origin master
        }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
